name       : at-spi2
version    : 2.20.2
release    : 11
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/at-spi2-core/2.20/at-spi2-core-2.20.2.tar.xz : 88a4de9d43139f13cca531b47b901bc1b56e0ab06ba899126644abd4ac16a143
license    :
    - GPL-3.0
summary    : Accessibility toolkit
builddeps  :
    - pkgconfig(gobject-2.0)
    - pkgconfig32(gobject-2.0)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - pkgconfig(xtst)
    - pkgconfig32(xtst)
    - pkgconfig(xi)
    - pkgconfig32(xi)
    - pkgconfig32(dbus-1)
    - glibc-32bit-devel
    - libgcc-32bit
    - dbus-32bit
emul32     : yes
description: |
    ATK provides the set of accessibility interfaces that are implemented by other toolkits and applications. Using the ATK interfaces, accessibility tools have full access to view and control running applications.
setup      : |
    %configure --libexecdir=/usr/lib64/at-spi2/core --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg
    rmdir $installdir/etc
