name       : at-spi2
version    : 2.36.0
release    : 23
source     :
    - https://download.gnome.org/sources/at-spi2-core/2.36/at-spi2-core-2.36.0.tar.xz : 88da57de0a7e3c60bc341a974a80fdba091612db3547c410d6deab039ca5c05a
license    : LGPL-2.1-or-later
component  : desktop.gtk
summary    : Accessibility toolkit
description: |
    ATK provides the set of accessibility interfaces that are implemented by other toolkits and applications. Using the ATK interfaces, accessibility tools have full access to view and control running applications.
emul32     : yes
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(liblzma)
    - pkgconfig32(x11)
    - pkgconfig32(xtst)
    - pkgconfig32(xi)
    - gtk-doc
    - libgcrypt-32bit-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-XDG-autostart-dir.-Enforce-previous-ex.patch
    %meson_configure -Ddocs=true
build      : |
    %ninja_build
install    : |
    %ninja_install
