name       : at-spi2
version    : 2.46.0
release    : 30
source     :
    - https://download.gnome.org/sources/at-spi2-core/2.46/at-spi2-core-2.46.0.tar.xz : aa0c86c79f7a8d67bae49a5b7a5ab08430c608cffe6e33bf47a72f41ab03c3d0
license    : LGPL-2.1-or-later
component  : desktop.gtk
summary    : Accessibility toolkit
description: |
    ATK provides the set of accessibility interfaces that are implemented by other toolkits and applications. Using the ATK interfaces, accessibility tools have full access to view and control running applications.
emul32     : yes
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(liblzma)
    - pkgconfig32(libzstd)
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(x11)
    - pkgconfig32(xtst)
    - pkgconfig32(xi)
    - libgcrypt-32bit-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-XDG-autostart-dir.-Enforce-previous-ex.patch
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        build_gobject="no"
    else
        build_gobject="yes"
    fi

    %meson_configure -Dintrospection=$build_gobject
build      : |
    %ninja_build
install    : |
    %ninja_install
