name       : at-spi2
version    : 2.18.1
release    : 10
source     :
    - http://ftp.gnome.org/pub/gnome/sources/at-spi2-core/2.18/at-spi2-core-2.18.1.tar.xz : 57d555be4cc64905454687bf9bb7dc1e68531bee93befa77222d94ea083f01cf
license    :
    - GPL-3.0
summary    : Accessibility toolkit
builddeps  :
    - pkgconfig(gobject-2.0)
    - pkgconfig32(gobject-2.0)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - pkgconfig(xtst)
    - pkgconfig32(xtst)
    - pkgconfig(xi)
    - pkgconfig32(xi)
    - pkgconfig32(dbus-1)
    - glibc-32bit-devel
    - libgcc-32bit
    - dbus-32bit
emul32     : yes
description: |
    ATK provides the set of accessibility interfaces that are implemented by other toolkits and applications. Using the ATK interfaces, accessibility tools have full access to view and control running applications.
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration-by-default.patch
    autoreconf -vfi
    %configure --libexecdir=/usr/lib64/at-spi2/core --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg
    rmdir $installdir/etc
