name       : at-spi2
version    : 2.48.3
release    : 38
source     :
    - https://download.gnome.org/sources/at-spi2-core/2.48/at-spi2-core-2.48.3.tar.xz : 37316df43ca9989ce539d54cf429a768c28bb38a0b34950beadd0421827edf55
license    : LGPL-2.1-or-later
component  : desktop.gtk
summary    : Accessibility toolkit
description: |
    ATK provides the set of accessibility interfaces that are implemented by other toolkits and applications. Using the ATK interfaces, accessibility tools have full access to view and control running applications.
emul32     : yes
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(libgcrypt)
    - pkgconfig32(liblzma)
    - pkgconfig32(libsystemd)
    - pkgconfig32(libzstd)
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(x11)
    - pkgconfig32(xtst)
    - pkgconfig32(xi)
    - dbus-broker
replaces   :
    - at-spi2-atk
    - libatk
    - 32bit : at-spi2-atk-32bit
    - 32bit : libatk-32bit
    - 32bit-dbginfo : libatk-32bit-dbginfo
    - 32bit-dbginfo : at-spi2-atk-32bit-dbginfo
    - 32bit-devel : at-spi2-atk-32bit-devel
    - 32bit-devel : libatk-32bit-devel
    - dbginfo : libatk-dbginfo
    - dbginfo : at-spi2-atk-dbginfo
    - devel : at-spi2-atk-devel
    - devel : libatk-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-XDG-autostart-dir.-Enforce-previous-ex.patch
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        build_gobject="disabled"
    else
        build_gobject="enabled"
    fi

    %meson_configure -Dintrospection=$build_gobject \
                     -Ddefault_bus=dbus-broker
build      : |
    %ninja_build
install    : |
    %ninja_install
