name        : at-spi2
version     : 2.18.1
release     : 8
source     :
    - http://ftp.gnome.org/pub/gnome/sources/at-spi2-core/2.18/at-spi2-core-2.18.1.tar.xz : 57d555be4cc64905454687bf9bb7dc1e68531bee93befa77222d94ea083f01cf
license     :
    - GPL-3.0
summary     : Accessibility toolkit
builddeps   :
    - pkgconfig(gobject-2.0)
    - pkgconfig(x11)
    - pkgconfig(xtst)
    - pkgconfig(xi)
description : |
    ATK provides the set of accessibility interfaces that are implemented by other toolkits and applications. Using the ATK interfaces, accessibility tools have full access to view and control running applications.
setup      : |
    %configure --libexecdir=%libdir%/at-spi2/core
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg
    
    # TODO: Address /etc/at-spi2/accessibility.conf
