name       : at-spi2
version    : 2.28.0
release    : 20
source     :
    - https://download.gnome.org/sources/at-spi2-core/2.28/at-spi2-core-2.28.0.tar.xz : 42a2487ab11ce43c288e73b2668ef8b1ab40a0e2b4f94e80fca04ad27b6f1c87
license    : GPL-3.0-or-later
component  : desktop.gtk
summary    : Accessibility toolkit
description: |
    ATK provides the set of accessibility interfaces that are implemented by other toolkits and applications. Using the ATK interfaces, accessibility tools have full access to view and control running applications.
emul32     : yes
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(liblzma)
    - pkgconfig32(x11)
    - pkgconfig32(xtst)
    - pkgconfig32(xi)
    - gtk-doc
    - libgcrypt-32bit-devel
setup      : |
    %apply_patches
    %meson_configure -Denable_docs=true
build      : |
    %ninja_build
install    : |
    %ninja_install
