name       : at-spi2
version    : 2.32.1
release    : 21
source     :
    - https://download.gnome.org/sources/at-spi2-core/2.32/at-spi2-core-2.32.1.tar.xz : 3c2aa937ebfaca2c86569bce9b16a34fbe20d69ef0c58846313b1c42f53b0d53
license    : GPL-3.0-or-later
component  : desktop.gtk
summary    : Accessibility toolkit
description: |
    ATK provides the set of accessibility interfaces that are implemented by other toolkits and applications. Using the ATK interfaces, accessibility tools have full access to view and control running applications.
emul32     : yes
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(liblzma)
    - pkgconfig32(x11)
    - pkgconfig32(xtst)
    - pkgconfig32(xi)
    - gtk-doc
    - libgcrypt-32bit-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-XDG-autostart-dir.-Enforce-previous-ex.patch
    %meson_configure -Ddocs=true
build      : |
    %ninja_build
install    : |
    %ninja_install
