name       : at-spi2
version    : 2.40.0
release    : 25
source     :
    - https://download.gnome.org/sources/at-spi2-core/2.40/at-spi2-core-2.40.0.tar.xz : 4196a7d30a0051e52a67b8ce4283fe79ae5e4e14a725719934565adf1d333429
license    : LGPL-2.1-or-later
component  : desktop.gtk
summary    : Accessibility toolkit
description: |
    ATK provides the set of accessibility interfaces that are implemented by other toolkits and applications. Using the ATK interfaces, accessibility tools have full access to view and control running applications.
emul32     : yes
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(liblzma)
    - pkgconfig32(x11)
    - pkgconfig32(xtst)
    - pkgconfig32(xi)
    - libgcrypt-32bit-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-XDG-autostart-dir.-Enforce-previous-ex.patch
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        build_gobject="no"
    else
        build_gobject="yes"
    fi

    %meson_configure -Dintrospection=$build_gobject
build      : |
    %ninja_build
install    : |
    %ninja_install
