name        : at-spi2
version     : 2.6.3
release     : 5
source      :
    - http://ftp.gnome.org/pub/gnome/sources/at-spi2-core/2.6/at-spi2-core-2.6.3.tar.xz : fc4487ae46e847cfd057b329b852cf99923772ecd2ddc29f29670c9f2b15d0ea
homepage    : http://www.gnome.org
license     :
    - GPL-3.0
summary     : Accessibility toolkit
builddeps   :
    - pkgconfig(gobject-2.0)
    - pkgconfig(x11)
    - pkgconfig(xtst)
    - pkgconfig(xi)
description : |
    ATK provides the set of accessibility interfaces that are implemented by other toolkits and applications. Using the ATK interfaces, accessibility tools have full access to view and control running applications.
setup      : |
    # TODO: Rename package, use less derpy libexec
    %configure --libexecdir=%libdir%/at-spi2/core
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg
    
    # TODO: Address /etc/at-spi2/accessibility.conf
