name       : at-spi2
version    : 2.26.2
release    : 16
source     :
    - https://download.gnome.org/sources/at-spi2-core/2.26/at-spi2-core-2.26.2.tar.xz : c80e0cdf5e3d713400315b63c7deffa561032a6c37289211d8afcfaa267c2615
license    : GPL-3.0
component  : desktop.gtk
emul32     : yes
summary    : Accessibility toolkit
description: |
    ATK provides the set of accessibility interfaces that are implemented by other toolkits and applications. Using the ATK interfaces, accessibility tools have full access to view and control running applications.
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(liblzma)
    - pkgconfig32(x11)
    - pkgconfig32(xtst)
    - pkgconfig32(xi)
    - glibc-32bit-devel
    - libgcc-32bit
    - libgcrypt-32bit-devel
setup      : |
    %configure --libexecdir=%libdir%/at-spi2/core --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg
    rmdir $installdir/etc
