name       : at-spi2
version    : 2.22.0
release    : 12
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/at-spi2-core/2.22/at-spi2-core-2.22.0.tar.xz : 415ea3af21318308798e098be8b3a17b2f0cf2fe16cecde5ad840cf4e0f2c80a
license    :
    - GPL-3.0
summary    : Accessibility toolkit
builddeps  :
    - pkgconfig(gobject-2.0)
    - pkgconfig32(gobject-2.0)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - pkgconfig(xtst)
    - pkgconfig32(xtst)
    - pkgconfig(xi)
    - pkgconfig32(xi)
    - pkgconfig32(dbus-1)
    - glibc-32bit-devel
    - libgcc-32bit
    - dbus-32bit
emul32     : yes
component  : desktop.gtk
description: |
    ATK provides the set of accessibility interfaces that are implemented by other toolkits and applications. Using the ATK interfaces, accessibility tools have full access to view and control running applications.
setup      : |
    %configure --libexecdir=%libdir%/at-spi2/core --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg
    rmdir $installdir/etc
