name       : at-spi2
version    : 2.26.0
release    : 15
source     :
    - https://download.gnome.org/sources/at-spi2-core/2.26/at-spi2-core-2.26.0.tar.xz : 511568a65fda11fdd5ba5d4adfd48d5d76810d0e6ba4f7460f1b2ec0dbbbc337
license    :
    - GPL-3.0
summary    : Accessibility toolkit
builddeps  :
    - pkgconfig(gobject-2.0)
    - pkgconfig32(gobject-2.0)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - pkgconfig(xtst)
    - pkgconfig32(xtst)
    - pkgconfig(xi)
    - pkgconfig32(xi)
    - pkgconfig32(dbus-1)
    - glibc-32bit-devel
    - libgcc-32bit
    - dbus-32bit
emul32     : yes
component  : desktop.gtk
description: |
    ATK provides the set of accessibility interfaces that are implemented by other toolkits and applications. Using the ATK interfaces, accessibility tools have full access to view and control running applications.
setup      : |
    %configure --libexecdir=%libdir%/at-spi2/core --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg
    rmdir $installdir/etc
